### ISSUE TITLE
Title of the Message

### ISSUE THREAD

**Issue by Dartui** [Spomky-Labs/web-push#5]
**Is your feature request related to a problem? Please describe.**

I wonder why there is no method for setting/getting Title of the Message? I don't know if this package is written over some RFC which does not describe, or even require Title, but Web Notifications has separate field for it (first argument): https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification#parameters

For me that would be nice addition to already great and fluent API you have made.

**Describe the solution you'd like**

Two new methods in `WebPush\Message` class: `withTitle` and `getTitle`.

**Describe alternatives you've considered**

For now I am using `withData(['title' => 'Notification title'])` to achieve this behavior.

**Additional context**

**Comment by Spomky** [comment]
Hi @Dartui,

You are right, this property is missing.
It will be added to the branch v1.1 to be released by the end of the month.

**Comment by Spomky** [comment]
Closing as I created the PR #6 for that issue.
Please continue the discussing there.
